# *** NEED MANUAL CREATION ***
#
# The root folder
PROJECT_FOLDER = 'D:/meteor-monitor'

# *** NEED MANUAL CREATION ***
#
# The original sample video data for training
ORIGINAL_DATA_FOLDER = '%s/data' % PROJECT_FOLDER

# *** NEED MANUAL CREATION ***
# /project/
#          data/
#               Meteor/
#                     video/
#
# The meteor data files, including original videos,
# preprocessed data files, are in this folder
METEOR_DATA_FOLDER = '%s/Meteor' % ORIGINAL_DATA_FOLDER

# *** NEED MANUAL CREATION ***
#
# Where the original video files stored
METEOR_VIDEO_FILE_FOLDER = '%s/video' % METEOR_DATA_FOLDER

# *** NEED MANUAL CREATION ***
# /project/
#          data/
#               Others/
#                     video/
#
# All non-meteor video/preprocessed data files are in this folder
OTHERS_DATA_FOLDER = '%s/Others' % ORIGINAL_DATA_FOLDER

# *** NEED MANUAL CREATION ***
#
# Where the original video files stored
OTHERS_VIDEO_FILE_FOLDER = '%s/video' % OTHERS_DATA_FOLDER


# ***** AUTOMATIC CREATION *****
#
# This is used to create sub-folder for data generated by
# different kind of pre-processed method.
#
# Generated data stored like this:
#
# /project/
#          data/
#               Meteor/
#                     Processed-method1/
#                                      (several sub-folders)
#
# *** NOTE: ***
# The 'Processed-method1' folder and corresponding
# sub-folders will be generated by the code automatically
PRE_PROCESSED_METHOD = 'Processed-method1'

# *** NEED MANUAL INSTALLATION and update ***
# ffmpeg used for video file processing
FFMPEG_COMMAND = 'D:/Software/ffmpeg-20180226-f4709f1-win64-static/bin/ffmpeg'

# *** NEED MANUAL CREATION ***
#
# Training sample folder
# TRAINING_FOLDER = '%s/Training' % PROJECT_FOLDER
TRAINING_FOLDER = '%s/360-cropped-subtracted' % PROJECT_FOLDER


# For CONV_RNN network output
NB_CLASSES = 2

# All videos' image frames are to be bin-ed to a fixed size sequence
SEQ_LENGTH = 60

# IMAGE_HEIGHT = 288
IMAGE_HEIGHT = 280
IMAGE_WIDTH = 360

# IMAGE_SHAPE = (IMAGE_HEIGHT, IMAGE_WIDTH, 3)
IMAGE_SHAPE = (IMAGE_HEIGHT, IMAGE_WIDTH, 1) # Need to feed with gray-scale images
VIDEO_FRAME_SHAPE = (SEQ_LENGTH, IMAGE_HEIGHT, IMAGE_WIDTH, 1)
